function cV = calcVdotCV2(p1,p2,Cd,rho,Rt,Dh,v,k1,av1,av2,av3,k2)
%CALCVDOTCV2
%    CV = CALCVDOTCV2(P1,P2,CD,RHO,RT,DH,V,K1,AV1,AV2,AV3,K2)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    24-Feb-2013 01:12:18

t2 = p1-p2;
t3 = av3-p1+p2;
t4 = k2.*t3;
t5 = tanh(t4);
t6 = av1-av2.*t5;
cV = Cd.*t6.*sqrt((t2.*tanh(k1.*t2).*2.0)./rho+1.0./Cd.^2.*1.0./Dh.^2.*Rt.^2.*v.^2.*(1.0./4.0))-(Rt.*t6.*v.*(1.0./2.0))./Dh;
