function prettyPlot(hx, hy, ht, hl)

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hx, hy, ht], ...
    'FontName'   , 'AvantGarde');


set([hl, gca]             , ...
    'FontSize'   , 11           );

set([hx, hy,  ht]  , ...
    'FontSize'   , 14          );
set( ht                    , ...
    'FontSize'   , 16          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 2         );
